version: "3.9"

services:
  facturacion:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - "nonexistent:latest"
    ports:
      - 8281:8281
    restart: always
    environment:
      - CUIT=23236938409
      - CERT=dqmdz.crt
      - PRIVATEKEY=dqmdz.key
      - PRODUCTION=FALSE
