name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create secret files
      run: |
        echo "${{ secrets.USER_CRT }}" > ${{ secrets.CERT_NAME }}.crt
        echo "${{ secrets.USER_KEY }}" > ${{ secrets.CERT_NAME }}.key

    - name: Set VERSION environment variable
      id: version
      run: echo "VERSION=v$(date +'%Y.%m.%d')-build${{ github.run_number }}" >> $GITHUB_ENV
  
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image with tags
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_IMAGE_NAME }}:latest
          ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}
